apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: istio-canary
spec:
  destination:
    name: myweb-service
  route:
  - labels:
      version: v1
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: istio-canary-tester
spec:
  destination:
    name: myweb-service
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(usertype=tester)(;.*)?$"
  route:
  - labels:
      version: v2
