apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: net-mypolicy
  namespace: default
spec:
  podSelector:
    matchLabels:
      netClass: db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          netClass: web
    ports:
    - protocol: TCP
      port: 3306