kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv-claim
spec:
  storageClassName: managed-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi